// <auto-generated />
using MachineCalculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MachineCalculator.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MachineCalculator.Models.AppData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CPU");

                    b.Property<double>("RAM");

                    b.Property<bool>("flag");

                    b.Property<int>("instances");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("AppDatas");
                });

            modelBuilder.Entity("MachineCalculator.Models.Parameter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppId");

                    b.Property<double>("load");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("AppId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("MachineCalculator.Models.Parameter", b =>
                {
                    b.HasOne("MachineCalculator.Models.AppData", "AppData")
                        .WithMany("resourses")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
